# Generated by Django 4.0.3 on 2022-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('isRank', models.BooleanField()),
                ('winner_name', models.CharField(max_length=50)),
                ('winner_god_1', models.CharField(max_length=20)),
                ('winner_god_2', models.CharField(max_length=20)),
                ('winner_god_ban', models.CharField(max_length=20)),
                ('winner_deck_code', models.CharField(max_length=30)),
                ('winner_normal_card_1', models.CharField(max_length=20)),
                ('winner_normal_card_2', models.CharField(max_length=20)),
                ('winner_normal_card_3', models.CharField(max_length=20)),
                ('winner_normal_card_4', models.CharField(max_length=20)),
                ('winner_normal_card_5', models.CharField(max_length=20)),
                ('winner_normal_card_6', models.CharField(max_length=20)),
                ('winner_normal_card_7', models.CharField(max_length=20)),
                ('winner_special_card_1', models.CharField(max_length=20)),
                ('winner_special_card_2', models.CharField(max_length=20)),
                ('winner_special_card_3', models.CharField(max_length=20)),
                ('loser_name', models.CharField(max_length=50)),
                ('loser_god_1', models.CharField(max_length=20)),
                ('loser_god_2', models.CharField(max_length=20)),
                ('loser_god_ban', models.CharField(max_length=20)),
                ('loser_deck_code', models.CharField(max_length=30)),
                ('loser_normal_card_1', models.CharField(max_length=20)),
                ('loser_normal_card_2', models.CharField(max_length=20)),
                ('loser_normal_card_3', models.CharField(max_length=20)),
                ('loser_normal_card_4', models.CharField(max_length=20)),
                ('loser_normal_card_5', models.CharField(max_length=20)),
                ('loser_normal_card_6', models.CharField(max_length=20)),
                ('loser_normal_card_7', models.CharField(max_length=20)),
                ('loser_special_card_1', models.CharField(max_length=20)),
                ('loser_special_card_2', models.CharField(max_length=20)),
                ('loser_special_card_3', models.CharField(max_length=20)),
            ],
        ),
    ]
