# Generated by Django 4.0.3 on 2022-08-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_code', models.CharField(max_length=20)),
                ('god_name', models.CharField(max_length=20)),
                ('god_keyword', models.CharField(max_length=10)),
                ('god_text', models.CharField(max_length=200)),
                ('pick_count', models.IntegerField()),
                ('pick_ratio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ban_count', models.IntegerField()),
                ('ban_ratio', models.DecimalField(decimal_places=1, max_digits=3)),
                ('win_count', models.IntegerField()),
                ('win_ratio', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='TotalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
    ]
