# Generated by Django 4.0.3 on 2022-08-26 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_god_ban_ratio_alter_god_pick_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(max_length=200)),
                ('god_code', models.CharField(max_length=20)),
                ('card_name', models.IntegerField()),
                ('pick_count', models.IntegerField()),
                ('pick_ratio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('win_count', models.IntegerField()),
                ('win_ratio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('god_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.god')),
            ],
        ),
    ]
