# Generated by Django 4.0.3 on 2022-08-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_card_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='god_id',
            new_name='god',
        ),
    ]
