# Generated by Django 4.0.3 on 2022-08-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_god_god_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField()),
                ('pick_ratio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('win_count', models.IntegerField()),
                ('win_ratio', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gods', models.ManyToManyField(to='api.god')),
            ],
        ),
    ]
