# Generated by Django 4.0.3 on 2022-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_partner_pick_ratio_alter_partner_win_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='win_ratio',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
