# Generated by Django 4.0.3 on 2022-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_partner_win_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dual',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
